package cmd

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/charmbracelet/huh"
	"github.com/fjbender/mollie-cli/internal/mollieclient"
	"github.com/fjbender/mollie-cli/internal/output"
	"github.com/fjbender/mollie-cli/internal/prompt"
	"github.com/mollie/mollie-api-golang/models/components"
	"github.com/mollie/mollie-api-golang/models/operations"
	"github.com/spf13/cobra"
)

// ── flag value holders ────────────────────────────────────────────────────────────────────────────

var (
	// create flags
	subCreateAmount      string
	subCreateCurrency    string
	subCreateInterval    string
	subCreateDescription string
	subCreateStartDate   string
	subCreateTimes       int64
	subCreateMethod      string
	subCreateWebhookURL  string
	subCreateMetadata    string
	subCreateMandateID   string

	// list flags
	subListLimit int64
	subListFrom  string

	// list-all flags
	subAllLimit int64
	subAllFrom  string

	// update flags
	subUpdateAmount      string
	subUpdateCurrency    string
	subUpdateInterval    string
	subUpdateDescription string
	subUpdateStartDate   string
	subUpdateTimes       int64
	subUpdateWebhookURL  string
	subUpdateMetadata    string
	subUpdateMandateID   string

	// cancel flag
	subCancelConfirm bool

	// payments list flags
	subPayLimit int64
	subPayFrom  string
)

// ── command tree ────────────────────────────────────────────────────────────────────────────────

var subscriptionsCmd = &cobra.Command{
	Use:   "subscriptions",
	Short: "Manage Mollie subscriptions",
}

var subscriptionsCreateCmd = &cobra.Command{
	Use:         "create <customer-id>",
	Short:       "Create a subscription for a customer",
	Args:        cobra.ExactArgs(1),
	RunE:        runSubscriptionsCreate,
	Annotations: map[string]string{"usesDefaults": "true"},
}

var subscriptionsListCmd = &cobra.Command{
	Use:   "list <customer-id>",
	Short: "List subscriptions for a customer",
	Args:  cobra.ExactArgs(1),
	RunE:  runSubscriptionsList,
}

var subscriptionsListAllCmd = &cobra.Command{
	Use:   "list-all",
	Short: "List all subscriptions across all customers",
	RunE:  runSubscriptionsListAll,
}

var subscriptionsGetCmd = &cobra.Command{
	Use:   "get <customer-id> <subscription-id>",
	Short: "Get a subscription",
	Args:  cobra.ExactArgs(2),
	RunE:  runSubscriptionsGet,
}

var subscriptionsUpdateCmd = &cobra.Command{
	Use:   "update <customer-id> <subscription-id>",
	Short: "Update a subscription",
	Args:  cobra.ExactArgs(2),
	RunE:  runSubscriptionsUpdate,
}

var subscriptionsCancelCmd = &cobra.Command{
	Use:   "cancel <customer-id> <subscription-id>",
	Short: "Cancel a subscription",
	Args:  cobra.ExactArgs(2),
	RunE:  runSubscriptionsCancel,
}

var subscriptionsPaymentsCmd = &cobra.Command{
	Use:   "payments <customer-id> <subscription-id>",
	Short: "List payments generated by a subscription",
	Args:  cobra.ExactArgs(2),
	RunE:  runSubscriptionsPayments,
}

func init() {
	// create flags
	subscriptionsCreateCmd.Flags().StringVar(&subCreateAmount, "amount", "", "Subscription amount, e.g. 10.00 (required; falls back to `defaults set --amount`)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateCurrency, "currency", "", "ISO 4217 currency code, e.g. EUR (required; falls back to `defaults set --currency`)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateInterval, "interval", "", "Payment interval, e.g. '1 month', '14 days' (required)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateDescription, "description", "", "Subscription description (required; falls back to `defaults set --description`)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateStartDate, "start-date", "", "Start date in YYYY-MM-DD format")
	subscriptionsCreateCmd.Flags().Int64Var(&subCreateTimes, "times", 0, "Total number of payments (0 = unlimited)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateMethod, "method", "", "Payment method for this subscription")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateWebhookURL, "webhook-url", "", "Webhook URL for payment status updates (falls back to `defaults set --webhook-url`)")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateMetadata, "metadata", "", "Arbitrary JSON metadata")
	subscriptionsCreateCmd.Flags().StringVar(&subCreateMandateID, "mandate-id", "", "Specific mandate ID to use")
	subscriptionsCreateCmd.MarkFlagRequired("interval") //nolint:errcheck

	// list flags
	subscriptionsListCmd.Flags().Int64Var(&subListLimit, "limit", 50, "Maximum number of results to return")
	subscriptionsListCmd.Flags().StringVar(&subListFrom, "from", "", "Return results starting from this subscription ID (cursor pagination)")

	// list-all flags
	subscriptionsListAllCmd.Flags().Int64Var(&subAllLimit, "limit", 50, "Maximum number of results to return")
	subscriptionsListAllCmd.Flags().StringVar(&subAllFrom, "from", "", "Return results starting from this subscription ID (cursor pagination)")

	// update flags
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateAmount, "amount", "", "New subscription amount")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateCurrency, "currency", "", "ISO 4217 currency code (required if --amount is set)")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateInterval, "interval", "", "New payment interval, e.g. '1 month'")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateDescription, "description", "", "New description")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateStartDate, "start-date", "", "New start date in YYYY-MM-DD format")
	subscriptionsUpdateCmd.Flags().Int64Var(&subUpdateTimes, "times", 0, "New total number of payments (0 = keep current)")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateWebhookURL, "webhook-url", "", "New webhook URL")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateMetadata, "metadata", "", "New metadata (JSON string)")
	subscriptionsUpdateCmd.Flags().StringVar(&subUpdateMandateID, "mandate-id", "", "New mandate ID")

	// cancel flag
	subscriptionsCancelCmd.Flags().BoolVar(&subCancelConfirm, "confirm", false, "Skip the confirmation prompt")

	// payments list flags
	subscriptionsPaymentsCmd.Flags().Int64Var(&subPayLimit, "limit", 50, "Maximum number of results to return")
	subscriptionsPaymentsCmd.Flags().StringVar(&subPayFrom, "from", "", "Return results starting from this payment ID (cursor pagination)")

	subscriptionsCmd.AddCommand(subscriptionsCreateCmd)
	subscriptionsCmd.AddCommand(subscriptionsListCmd)
	subscriptionsCmd.AddCommand(subscriptionsListAllCmd)
	subscriptionsCmd.AddCommand(subscriptionsGetCmd)
	subscriptionsCmd.AddCommand(subscriptionsUpdateCmd)
	subscriptionsCmd.AddCommand(subscriptionsCancelCmd)
	subscriptionsCmd.AddCommand(subscriptionsPaymentsCmd)

	rootCmd.AddCommand(subscriptionsCmd)
}

// ── handlers ───────────────────────────────────────────────────────────────────────────────────

func runSubscriptionsCreate(cmd *cobra.Command, args []string) error {
	customerID := args[0]

	applyCreateDefaults(cmd,
		&subCreateDescription, &subCreateAmount, &subCreateCurrency,
		nil, &subCreateWebhookURL, // subscriptions have no redirect-url
	)

	// Validate fields that are required but may come from defaults.
	switch {
	case subCreateAmount == "":
		return fmt.Errorf("required flag \"amount\" not set and no default configured (run `mollie defaults set`)")
	case subCreateCurrency == "":
		return fmt.Errorf("required flag \"currency\" not set and no default configured (run `mollie defaults set`)")
	case subCreateDescription == "":
		return fmt.Errorf("required flag \"description\" not set and no default configured (run `mollie defaults set`)")
	}

	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	req := &components.SubscriptionRequest{
		Amount: &components.Amount{
			Currency: subCreateCurrency,
			Value:    subCreateAmount,
		},
		Interval:    &subCreateInterval,
		Description: &subCreateDescription,
	}
	if subCreateStartDate != "" {
		req.StartDate = &subCreateStartDate
	}
	if subCreateTimes > 0 {
		req.Times = &subCreateTimes
	}
	if subCreateMethod != "" {
		m := components.SubscriptionMethod(subCreateMethod)
		req.Method = &m
	}
	if subCreateWebhookURL != "" {
		req.WebhookURL = &subCreateWebhookURL
	}
	if subCreateMandateID != "" {
		req.MandateID = &subCreateMandateID
	}
	if subCreateMetadata != "" {
		meta, err := parseMetadata(subCreateMetadata)
		if err != nil {
			return fmt.Errorf("invalid --metadata: %w", err)
		}
		req.Metadata = &meta
	}

	resp, err := client.Subscriptions.Create(context.Background(), customerID, nil, req)
	if err != nil {
		return fmt.Errorf("creating subscription: %w", err)
	}
	s := resp.GetSubscriptionResponse()
	if s == nil {
		return fmt.Errorf("unexpected empty response from API")
	}

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(s)
	default:
		output.PrintTable(
			[]string{"ID", "STATUS", "AMOUNT", "INTERVAL", "DESCRIPTION"},
			[][]string{{
				s.GetID(),
				string(s.GetStatus()),
				formatAmount(s.GetAmount()),
				s.GetInterval(),
				s.GetDescription(),
			}},
			!flagLive,
		)
	}
	return nil
}

func runSubscriptionsList(_ *cobra.Command, args []string) error {
	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	req := operations.ListSubscriptionsRequest{
		CustomerID: args[0],
		Limit:      &subListLimit,
	}
	if subListFrom != "" {
		req.From = &subListFrom
	}

	resp, err := client.Subscriptions.List(context.Background(), req)
	if err != nil {
		return fmt.Errorf("listing subscriptions: %w", err)
	}
	if resp.Object == nil {
		return nil
	}

	subListEmbedded := resp.Object.GetEmbedded()
	subs := subListEmbedded.GetSubscriptions()

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(resp.Object)
	default:
		rows := make([][]string, 0, len(subs))
		for _, s := range subs {
			rows = append(rows, []string{
				s.GetID(),
				string(s.GetStatus()),
				formatAmount(s.GetAmount()),
				s.GetInterval(),
				s.GetDescription(),
			})
		}
		output.PrintTable(
			[]string{"ID", "STATUS", "AMOUNT", "INTERVAL", "DESCRIPTION"},
			rows,
			!flagLive,
		)
	}
	return nil
}

func runSubscriptionsListAll(_ *cobra.Command, _ []string) error {
	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	req := operations.ListAllSubscriptionsRequest{
		Limit: &subAllLimit,
	}
	if subAllFrom != "" {
		req.From = &subAllFrom
	}

	resp, err := client.Subscriptions.All(context.Background(), req)
	if err != nil {
		return fmt.Errorf("listing all subscriptions: %w", err)
	}
	if resp.Object == nil {
		return nil
	}

	subAllEmbedded := resp.Object.GetEmbedded()
	subs := subAllEmbedded.GetSubscriptions()

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(resp.Object)
	default:
		rows := make([][]string, 0, len(subs))
		for _, s := range subs {
			rows = append(rows, []string{
				s.GetID(),
				string(s.GetStatus()),
				formatAmount(s.GetAmount()),
				s.GetInterval(),
				s.GetCustomerID(),
				s.GetDescription(),
			})
		}
		output.PrintTable(
			[]string{"ID", "STATUS", "AMOUNT", "INTERVAL", "CUSTOMER ID", "DESCRIPTION"},
			rows,
			!flagLive,
		)
	}
	return nil
}

func runSubscriptionsGet(_ *cobra.Command, args []string) error {
	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	resp, err := client.Subscriptions.Get(context.Background(), args[0], args[1], nil, nil)
	if err != nil {
		return fmt.Errorf("getting subscription: %w", err)
	}
	s := resp.GetSubscriptionResponse()
	if s == nil {
		return fmt.Errorf("subscription not found")
	}

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(s)
	default:
		timesStr := "—"
		if t := s.GetTimes(); t != nil {
			timesStr = strconv.FormatInt(*t, 10)
		}
		timesRemainingStr := "—"
		if t := s.GetTimesRemaining(); t != nil {
			timesRemainingStr = strconv.FormatInt(*t, 10)
		}
		output.PrintTable(
			[]string{"FIELD", "VALUE"},
			[][]string{
				{"ID", s.GetID()},
				{"Mode", string(s.GetMode())},
				{"Status", string(s.GetStatus())},
				{"Amount", formatAmount(s.GetAmount())},
				{"Interval", s.GetInterval()},
				{"Description", s.GetDescription()},
				{"Start Date", s.GetStartDate()},
				{"Next Payment Date", derefOpt(s.GetNextPaymentDate())},
				{"Times", timesStr},
				{"Times Remaining", timesRemainingStr},
				{"Customer ID", s.GetCustomerID()},
				{"Mandate ID", derefOpt(s.GetMandateID())},
				{"Webhook URL", derefOpt(s.GetWebhookURL())},
				{"Created At", s.GetCreatedAt()},
				{"Canceled At", derefOpt(s.GetCanceledAt())},
			},
			!flagLive,
		)
	}
	return nil
}

func runSubscriptionsUpdate(_ *cobra.Command, args []string) error {
	customerID, subscriptionID := args[0], args[1]

	if (subUpdateAmount == "") != (subUpdateCurrency == "") {
		return fmt.Errorf("--amount and --currency must both be set")
	}

	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	body := &operations.UpdateSubscriptionRequestBody{}
	if subUpdateAmount != "" {
		body.Amount = &components.Amount{
			Currency: subUpdateCurrency,
			Value:    subUpdateAmount,
		}
	}
	if subUpdateInterval != "" {
		body.Interval = &subUpdateInterval
	}
	if subUpdateDescription != "" {
		body.Description = &subUpdateDescription
	}
	if subUpdateStartDate != "" {
		body.StartDate = &subUpdateStartDate
	}
	if subUpdateTimes > 0 {
		body.Times = &subUpdateTimes
	}
	if subUpdateWebhookURL != "" {
		body.WebhookURL = &subUpdateWebhookURL
	}
	if subUpdateMandateID != "" {
		body.MandateID = &subUpdateMandateID
	}
	if subUpdateMetadata != "" {
		meta, err := parseMetadata(subUpdateMetadata)
		if err != nil {
			return fmt.Errorf("invalid --metadata: %w", err)
		}
		body.Metadata = &meta
	}

	resp, err := client.Subscriptions.Update(context.Background(), customerID, subscriptionID, nil, body)
	if err != nil {
		return fmt.Errorf("updating subscription: %w", err)
	}

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(resp.GetSubscriptionResponse())
	default:
		fmt.Printf("✓ Subscription %s updated\n", subscriptionID)
	}
	return nil
}

func runSubscriptionsCancel(_ *cobra.Command, args []string) error {
	customerID, subscriptionID := args[0], args[1]

	if !subCancelConfirm {
		confirmed, err := prompt.Confirm(fmt.Sprintf("Cancel subscription %s for customer %s?", subscriptionID, customerID))
		if err != nil {
			if errors.Is(err, huh.ErrUserAborted) {
				fmt.Println("Cancelled.")
				return nil
			}
			return err
		}
		if !confirmed {
			fmt.Println("Cancelled.")
			return nil
		}
	}

	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	if _, err := client.Subscriptions.Cancel(context.Background(), customerID, subscriptionID, nil, nil); err != nil {
		return fmt.Errorf("canceling subscription: %w", err)
	}

	fmt.Printf("✓ Subscription %s canceled\n", subscriptionID)
	return nil
}

func runSubscriptionsPayments(_ *cobra.Command, args []string) error {
	client, err := mollieclient.New(cfg, flagAPIKey, flagLive, flagProfile)
	if err != nil {
		return err
	}

	req := operations.ListSubscriptionPaymentsRequest{
		CustomerID:     args[0],
		SubscriptionID: args[1],
		Limit:          &subPayLimit,
	}
	if subPayFrom != "" {
		req.From = &subPayFrom
	}

	resp, err := client.Subscriptions.ListPayments(context.Background(), req)
	if err != nil {
		return fmt.Errorf("listing subscription payments: %w", err)
	}
	if resp.Object == nil {
		return nil
	}

	subPayEmbedded := resp.Object.GetEmbedded()
	payments := subPayEmbedded.GetPayments()

	switch resolvedOutput() {
	case output.FormatJSON:
		return output.PrintJSON(resp.Object)
	default:
		rows := make([][]string, 0, len(payments))
		for _, p := range payments {
			rows = append(rows, []string{
				p.GetID(),
				string(p.GetStatus()),
				formatAmount(p.GetAmount()),
				p.GetCreatedAt(),
				p.GetDescription(),
			})
		}
		output.PrintTable(
			[]string{"ID", "STATUS", "AMOUNT", "CREATED AT", "DESCRIPTION"},
			rows,
			!flagLive,
		)
	}
	return nil
}
